apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor-service
  template:
    metadata:
      labels:
        app: monitor-service
    spec:
      containers:
        - name: monitor-service
          image: thoratshubham/monitor-service:v6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5002